// Code generated by swaggo/swag. DO NOT EDIT.
// Run `swag init -g internal/api/docs.go` to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Get a paginated list of users",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "List users",
                "parameters": [
                    {"type": "integer", "default": 0,  "description": "Offset", "name": "offset", "in": "query"},
                    {"type": "integer", "default": 20, "description": "Limit",  "name": "limit",  "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK",                    "schema": {"$ref": "#/definitions/service.ListUsersResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "post": {
                "description": "Create a new user and publish a CREATED event to Kafka",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Create a user",
                "parameters": [
                    {"description": "User payload", "name": "user", "in": "body", "required": true,
                     "schema": {"$ref": "#/definitions/service.CreateUserRequest"}}
                ],
                "responses": {
                    "201": {"description": "Created",     "schema": {"$ref": "#/definitions/models.User"}},
                    "400": {"description": "Bad Request", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get a single user by UUID",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Get a user",
                "parameters": [
                    {"type": "string", "description": "User UUID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/models.User"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "put": {
                "description": "Update an existing user and publish an UPDATED event to Kafka",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Update a user",
                "parameters": [
                    {"type": "string", "description": "User UUID", "name": "id", "in": "path", "required": true},
                    {"description": "Fields to update", "name": "user", "in": "body", "required": true,
                     "schema": {"$ref": "#/definitions/service.UpdateUserRequest"}}
                ],
                "responses": {
                    "200": {"description": "OK",        "schema": {"$ref": "#/definitions/models.User"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            },
            "delete": {
                "description": "Soft-delete a user and publish a DELETED event to Kafka",
                "tags": ["users"],
                "summary": "Delete a user",
                "parameters": [
                    {"type": "string", "description": "User UUID", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {"description": "Not Found", "schema": {"$ref": "#/definitions/ErrorResponse"}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "models.User": {
            "type": "object",
            "properties": {
                "id":         {"type": "string"},
                "name":       {"type": "string"},
                "email":      {"type": "string"},
                "age":        {"type": "integer"},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        },
        "service.CreateUserRequest": {
            "type": "object",
            "required": ["name", "email"],
            "properties": {
                "name":  {"type": "string"},
                "email": {"type": "string"},
                "age":   {"type": "integer"}
            }
        },
        "service.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "name":  {"type": "string"},
                "email": {"type": "string"},
                "age":   {"type": "integer"}
            }
        },
        "service.ListUsersResponse": {
            "type": "object",
            "properties": {
                "users":  {"type": "array", "items": {"$ref": "#/definitions/models.User"}},
                "total":  {"type": "integer"},
                "offset": {"type": "integer"},
                "limit":  {"type": "integer"}
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {"type": "string"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "User Kafka Go API",
	Description:      "CRUD API for users with dual-format Kafka event publishing (Avro + Protobuf).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
